## PEAS
### `P`: Cách tối ưu nhất để sạch nhà và tốn ít pin hay điện nhất
### `E`: Sàn nhà, kích thước sàn, bụi bẩn trên sàn nhà
### `A`: Các hàm để agent hiểu và thực hiện các hành động (tiến, lùi, qua trái, qua phải, quét bụi)
### `S`: Quét vị trí hiện tại, thông tin thông qua các cảm biến

In [12]:
import numpy as np
import random

In [23]:
row, col = 0, 0
count = 0

def create_matrix():
    global row, col
    
    size_m = int(input("Nhập vào chiều dài sàn nhà (m): "))
    size_n = int(input("Nhập vào chiều rộng sàn nhà (n): "))
    
    matrix = np.random.randint(0, 2, (size_m, size_n))
    
    row = random.randrange(size_m)
    col = random.randrange(size_n)
    
    return matrix, row, col

In [17]:
def valid_moves(matrix):
    
    global row, col
    
    list_of_directions = []
    size_mat = matrix.shape
    
    directions = [
        ['UP', 1, 0],
        ['DOWN', -1, 0],
        ['LEFT', 0, -1],
        ['RIGHT', 0, 1]
    ]
    
    for dir, x, y in directions:
        x_new = row + x
        y_new = col + y
        if x_new >= 0 and x_new < size_mat[0] and y_new >= 0 and y_new < size_mat[1]:
            list_of_directions.append([dir, x_new, y_new])
    
    return list_of_directions

In [ ]:
def run_reflex_agent(ini_matrix):
    global row, col, count
    
    cur_matrix = ini_matrix
    
    print("TRẠNG THÁI BAN ĐẦU")
    print(ini_matrix)
    print(f"MÁY HÚT BỤI ĐANG Ở VỊ TRÍ [{row}, {col}]")
    
    while True:
        if 1 not in cur_matrix:
            print("NHÀ ĐÃ SẠCH, MÁY NGỪNG LÀM VIỆC!!!")
            break
        
        if count == 100:
            print("BẾ TẮC, MÁY NGỪNG!!!")
            break
        
        if cur_matrix[row, col] == 1:
            print("VỊ TRÍ NHÀ BẨN TIẾN HÀNH LÀM SẠCH")
            cur_matrix[row, col] = 0
            count += 1
        
        moves = valid_moves(cur_matrix)
        
        direction, row, col = random.choice(moves)
        
        print(f"MAY HUT BUI DI CHUYEN {direction}")
        
        print(cur_matrix)

In [26]:
matrix_mxn, row, col = create_matrix()
run_reflex_agent(matrix_mxn)

TRANG THAI BAN DAU
[[1 1 1 1]
 [0 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DANG O VI TRI [1, 2]
VI TRI NHA BAN, TIEN HANH LAM SACH
MAY HUT BUI DI CHUYEN DOWN
[[1 1 1 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
VI TRI NHA BAN, TIEN HANH LAM SACH
MAY HUT BUI DI CHUYEN UP
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN UP
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN LEFT
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN RIGHT
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN DOWN
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN UP
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN LEFT
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN RIGHT
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
MAY HUT BUI DI CHUYEN UP
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 1]]
VI TRI NHA BAN, TIEN HANH LAM SACH
MAY HUT BUI DI CHUYEN RIGHT
[[1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 0 1]]
VI TRI NHA 