## PEAS
### `P`: Cách tối ưu nhất để sạch nhà và tốn ít pin hay điện nhất
### `E`: Sàn nhà, kích thước sàn, bụi bẩn trên sàn nhà
### `A`: Các hàm để agent hiểu và thực hiện các hành động (tiến, lùi, qua trái, qua phải, quét bụi)
### `S`: Quét vị trí hiện tại, thông tin thông qua các cảm biến

In [52]:
import numpy as np
import random

In [60]:
def create_matrix():
    
    size_m = int(input("Nhập vào chiều dài sàn nhà (m): "))
    size_n = int(input("Nhập vào chiều rộng sàn nhà (n): "))
    
    matrix = np.random.randint(0, 2, (size_m, size_n))
    
    row = random.randrange(size_m)
    col = random.randrange(size_n)
    
    return matrix, row, col

In [61]:
def valid_moves(matrix, row, col):
        
    list_of_directions = []
    size_mat = matrix.shape
    
    directions = [
        ['UP', -1, 0],
        ['DOWN', 1, 0],
        ['LEFT', 0, -1],
        ['RIGHT', 0, 1]
    ]
    
    for dir, x, y in directions:
        x_new = row + x
        y_new = col + y
        if x_new >= 0 and x_new < size_mat[0] and y_new >= 0 and y_new < size_mat[1]:
            list_of_directions.append([dir, x_new, y_new])
    
    return list_of_directions

In [64]:
def run_reflex_agent(ini_matrix, count, row, col):

    cur_matrix = ini_matrix
    
    print("TRẠNG THÁI BAN ĐẦU")
    print(ini_matrix)
    print(f"MÁY HÚT BỤI ĐANG Ở VỊ TRÍ [{row}, {col}]")
    
    while True:
        print(f"Máy chạy lần thứ: {count + 1}\n")
        
        if count == 100:
            print("BẾ TẮC, MÁY NGỪNG!!!")
            break
        
        if cur_matrix[row, col] == 1:
            print("VỊ TRÍ NHÀ BẨN TIẾN HÀNH LÀM SẠCH\n")
            cur_matrix[row, col] = 0
            
        if 1 not in cur_matrix:
            print("NHÀ ĐÃ SẠCH, MÁY NGỪNG LÀM VIỆC!!!")
            break
        
        count += 1
        
        moves = valid_moves(cur_matrix, row, col)
        
        direction, row, col = random.choice(moves)
        
        print(f"MÁY HÚT BỤI DI CHUYỂN {direction}, ĐẾN VỊ TRÍ [{row}, {col}]")
        
        print(cur_matrix)

In [66]:
matrix_mxn, row, col = create_matrix()
run_reflex_agent(matrix_mxn, 0, row, col)

TRẠNG THÁI BAN ĐẦU
[[1 0 1]
 [1 1 0]
 [0 0 1]]
MÁY HÚT BỤI ĐANG Ở VỊ TRÍ [2, 2]
Máy chạy lần thứ: 1

VỊ TRÍ NHÀ BẨN TIẾN HÀNH LÀM SẠCH

MÁY HÚT BỤI DI CHUYỂN UP, ĐẾN VỊ TRÍ [1, 2]
[[1 0 1]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 2

MÁY HÚT BỤI DI CHUYỂN UP, ĐẾN VỊ TRÍ [0, 2]
[[1 0 1]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 3

VỊ TRÍ NHÀ BẨN TIẾN HÀNH LÀM SẠCH

MÁY HÚT BỤI DI CHUYỂN LEFT, ĐẾN VỊ TRÍ [0, 1]
[[1 0 0]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 4

MÁY HÚT BỤI DI CHUYỂN RIGHT, ĐẾN VỊ TRÍ [0, 2]
[[1 0 0]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 5

MÁY HÚT BỤI DI CHUYỂN LEFT, ĐẾN VỊ TRÍ [0, 1]
[[1 0 0]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 6

MÁY HÚT BỤI DI CHUYỂN LEFT, ĐẾN VỊ TRÍ [0, 0]
[[1 0 0]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 7

VỊ TRÍ NHÀ BẨN TIẾN HÀNH LÀM SẠCH

MÁY HÚT BỤI DI CHUYỂN RIGHT, ĐẾN VỊ TRÍ [0, 1]
[[0 0 0]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 8

MÁY HÚT BỤI DI CHUYỂN RIGHT, ĐẾN VỊ TRÍ [0, 2]
[[0 0 0]
 [1 1 0]
 [0 0 0]]
Máy chạy lần thứ: 9

MÁY HÚT BỤI DI CHUYỂN DOWN, ĐẾN VỊ 