In [7]:
import numpy as np

In [17]:
class Node:
    
    def __init__(self, state, parent, action, path_cost):
        self.state = state
        self.parent = parent
        self.action = action
        self.path_cost = path_cost

In [18]:
def find_zero(matrix):
    
    vi_tri = np.argwhere(matrix == 0)[0]
    return vi_tri[0], vi_tri[1]

In [ ]:

def move(matrix):
    
    lst_move = []
    x, y = find_zero(matrix)
    
    directions = [
        ['UP', -1, 0],
        ['DOWN', 1, 0],
        ['LEFT', 0, -1],
        ['RIGHT', 0, 1]
    ]
    
    for dir, i, j in directions:
        x_new = x + i
        y_new = y + j
        
        if x_new < 3 and x_new >=0 and y_new < 3 and y_new >= 0:
            lst_move.append([dir, x_new, y_new])
            
    return lst_move

In [34]:
def solution(node):
    path = []
    
    while node.parent is not None:
        path.append((node.action, node.state))
        
        node = node.parent
        
    path.reverse()
    
    return path

In [41]:
def bfs(matrix, goal):
    node = Node(matrix, None, None, 0)
    
    if np.array_equal(node.state, goal):
        solutions = solution(node)
        for action, state in solutions:
            print("HUONG DI: ", action)
            print(state)
            print("DA HOAN THANH!!!")
        return
    
    frontier = []
    frontier_state = []
    frontier.append(node)
    frontier_state.append(tuple(map(tuple, matrix)))
    
    reached = []
    
    while len(frontier) != 0:
        
        node = frontier.pop(0)
        
        temp_mat = node.state.copy()
        
        temp_mat = tuple(map(tuple, temp_mat))
        
        if temp_mat not in reached:
            reached.append(temp_mat)
        
        if np.array_equal(node.state, goal):
            solutions = solution(node)
            for action, state in solutions:
                print("HUONG DI: ", action)
                print(state)
            return
        
        moves = move(node.state)
        
        x, y = find_zero(node.state)
        
        for m in moves:
            new_node = node.state.copy()
            new_node[x, y], new_node[m[1], m[2]] = new_node[m[1], m[2]], new_node[x, y]
            
            child = Node(new_node, node, m[0], node.path_cost + 1)
            
            new_node = tuple(map(tuple, new_node))
            if (new_node not in frontier_state) and (new_node not in reached):
                frontier.append(child)
                frontier_state.append(tuple(map(tuple, child.state)))
                
    return "KHONG TON TAI CACH GIAI!!!"

In [40]:
matrix = np.array([
    [5, 3, 0],
    [2, 8, 7],
    [1, 4, 6]
])
goal = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])

bfs(matrix, goal)

HUONG DI:  LEFT
[[5 0 3]
 [2 8 7]
 [1 4 6]]
HUONG DI:  LEFT
[[0 5 3]
 [2 8 7]
 [1 4 6]]
HUONG DI:  DOWN
[[2 5 3]
 [0 8 7]
 [1 4 6]]
HUONG DI:  DOWN
[[2 5 3]
 [1 8 7]
 [0 4 6]]
HUONG DI:  RIGHT
[[2 5 3]
 [1 8 7]
 [4 0 6]]
HUONG DI:  UP
[[2 5 3]
 [1 0 7]
 [4 8 6]]
HUONG DI:  RIGHT
[[2 5 3]
 [1 7 0]
 [4 8 6]]
HUONG DI:  DOWN
[[2 5 3]
 [1 7 6]
 [4 8 0]]
HUONG DI:  LEFT
[[2 5 3]
 [1 7 6]
 [4 0 8]]
HUONG DI:  UP
[[2 5 3]
 [1 0 6]
 [4 7 8]]
HUONG DI:  UP
[[2 0 3]
 [1 5 6]
 [4 7 8]]
HUONG DI:  LEFT
[[0 2 3]
 [1 5 6]
 [4 7 8]]
HUONG DI:  DOWN
[[1 2 3]
 [0 5 6]
 [4 7 8]]
HUONG DI:  DOWN
[[1 2 3]
 [4 5 6]
 [0 7 8]]
HUONG DI:  RIGHT
[[1 2 3]
 [4 5 6]
 [7 0 8]]
HUONG DI:  RIGHT
[[1 2 3]
 [4 5 6]
 [7 8 0]]
