### RULES

* Với mỗi trạng thái của puzzle, xác định vị trí số 0 sau đó xác định các hướng có thể đi như: `LEFT`, `RIGHT`, `UP`, `DOWN`
* Với mỗi hướng đi xác định trạng thái cũ đã tồn tại trước đó hay chưa
* Nếu đã tồn tại trạng thái ma trận trước đó thì xoá hướng đi hiện tại
* Nếu chưa tồn tại trạng thái ma trận trước đó thì tiến hành random các bước đi trong số bước còn lại

In [ ]:
import numpy as np
import random

In [74]:
def find_zero(matrix):
    vi_tri = np.argwhere(matrix == 0)[0]
    return vi_tri[0], vi_tri[1]

In [69]:
def rules(matrix):
    
    x, y = find_zero(matrix)
    
    lst_move = []
    
    directions = [
        ['UP', -1, 0],
        ['DOWN', 1, 0],
        ['LEFT', 0, -1],
        ['RIGHT', 0, 1]
    ]
    
    for dir, i, j in directions:
        x_new = x + i
        y_new = y + j
        
        if x_new < 3 and x_new >=0 and y_new < 3 and y_new >= 0:
            lst_move.append([dir, x_new, y_new])
            
    return lst_move

In [70]:
def check(matrix, dir):
    
    new_mat = matrix.copy()
    x, y = find_zero(matrix)
    
    if dir == 'UP':
        new_mat[x - 1, y], new_mat[x, y] = 0, new_mat[x - 1, y]
    elif dir == 'DOWN':
        new_mat[x + 1, y], new_mat[x, y] = 0, new_mat[x + 1, y]
    elif dir == 'RIGHT':
        new_mat[x, y + 1], new_mat[x, y] = 0, new_mat[x, y + 1]
    else:
       new_mat[x, y - 1], new_mat[x, y] = 0, new_mat[x, y - 1]
        
    return new_mat

In [71]:
goal = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,0]
])

def to_tuple(mat):
    return tuple(map(tuple, mat))

def actions(matrix):
    count = 0
    history = set()

    print('TRANG THAI BAN DAU')
    print(matrix, '\n')

    while True:
        
        current_state = to_tuple(matrix)

        if np.array_equal(matrix, goal):
            print("ĐÃ GIẢI ĐƯỢC 8 PUZZLE!!!")
            print(f"SỐ LẦN CHẠY: {count}")
            break
        
        if current_state in history:
            print("\n[DỪNG] Trùng trạng thái cũ.")
            print(f"SỐ LẦN CHẠY: {count}")
            break
        
        count += 1
        
        history.add(current_state)

        moves = rules(matrix)

        valid_moves = []

        for x in moves:

            new_mat = check(matrix, x[0])

            new_state = to_tuple(new_mat)

            if new_state not in history:
                valid_moves.append(x)

        moves = valid_moves

        if len(moves) == 0:
            print("DỪNG VÌ KHÔNG CÒN NƯỚC ĐI!!!")
            print(f"SỐ LẦN CHẠY: {count}")
            break

        dir, row, col = random.choice(moves)

        x_zero, y_zero = find_zero(matrix)

        print(f"DI CHUYỂN {dir} \n")

        matrix[x_zero, y_zero], matrix[row, col] = matrix[row, col], matrix[x_zero, y_zero]

        print("TRẠNG THÁI HIỆN TẠI")
        print(matrix, '\n')

In [72]:
def create_mat():
    lst_number = list(range(9))
    
    np.random.shuffle(lst_number)
    
    board = np.array(lst_number).reshape(3, 3)
    
    return board

In [75]:
matrix = create_mat()
actions(matrix)

TRANG THAI BAN DAU
[[5 3 7]
 [6 8 0]
 [2 4 1]] 

DI CHUYỂN DOWN 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 8 1]
 [2 4 0]] 

DI CHUYỂN LEFT 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 8 1]
 [2 0 4]] 

DI CHUYỂN UP 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 0 1]
 [2 8 4]] 

DI CHUYỂN RIGHT 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 1 0]
 [2 8 4]] 

DI CHUYỂN DOWN 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 1 4]
 [2 8 0]] 

DI CHUYỂN LEFT 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 1 4]
 [2 0 8]] 

DI CHUYỂN LEFT 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [6 1 4]
 [0 2 8]] 

DI CHUYỂN UP 

TRẠNG THÁI HIỆN TẠI
[[5 3 7]
 [0 1 4]
 [6 2 8]] 

DI CHUYỂN UP 

TRẠNG THÁI HIỆN TẠI
[[0 3 7]
 [5 1 4]
 [6 2 8]] 

DI CHUYỂN RIGHT 

TRẠNG THÁI HIỆN TẠI
[[3 0 7]
 [5 1 4]
 [6 2 8]] 

DI CHUYỂN DOWN 

TRẠNG THÁI HIỆN TẠI
[[3 1 7]
 [5 0 4]
 [6 2 8]] 

DI CHUYỂN LEFT 

TRẠNG THÁI HIỆN TẠI
[[3 1 7]
 [0 5 4]
 [6 2 8]] 

DI CHUYỂN UP 

TRẠNG THÁI HIỆN TẠI
[[0 1 7]
 [3 5 4]
 [6 2 8]] 

DI CHUYỂN RIGHT 

TRẠNG THÁI HIỆN TẠI
[[1 0 7]
 [3 5 4]
 [6 2 8]] 

DI CHUYỂN DOWN 

T