In [1]:
import numpy as np
import random

In [16]:
def create_mat():
    
    size_m = int(input("Nhập vào chiều dài sàn nhà (m): "))
    size_n = int(input("Nhập vào chiều rộng sàn nhà (n): "))
    
    matrix = np.random.randint(0, 3, (size_m, size_n))
    
    row = random.randrange(size_m)
    col = random.randrange(size_n)
    
    while (matrix[row, col] == 2):
        row = random.randrange(size_m)
        col = random.randrange(size_n)
        
    return matrix, row, col

In [ ]:
def rules(matrix, row, col):
    
    lst_move = []
    size = matrix.shape
    
    directions = [
        ['UP', -1, 0],
        ['DOWN', 1, 0],
        ['LEFT', 0, -1],
        ['RIGHT', 0, 1]
    ]
    
    for dir, i, j in directions:
        x_new = row + i
        y_new = col + j
        
        if x_new < size[0] and x_new >= 0 and y_new < size[1] and y_new >= 0 and matrix[x_new, y_new] != 2:
            lst_move.append([dir, x_new, y_new])
            
    return lst_move

In [4]:
def check(matrix, dir, row, col):
    new_mat = matrix.copy()
    
    if dir == 'UP':
        new_mat[row - 1, col], new_mat[row, col] = 0, new_mat[row - 1, col]
    elif dir == 'DOWN':
        new_mat[row + 1, col], new_mat[row, col] = 0, new_mat[row + 1, col]
    elif dir == 'RIGHT':
        new_mat[row, col + 1], new_mat[row, col] = 0, new_mat[row, col + 1]
    else:
       new_mat[row, col - 1], new_mat[row, col] = 0, new_mat[row, col - 1]
       
    return new_mat

In [28]:
def actions(matrix, row, col):
    
    history = []
    print(f"VI TRI BAN DAU CUA MAY [{row}, {col}]")
    print(matrix)
    
    while True:
        
        moves = rules(matrix, row, col)
        
        if len(moves) == 0:
            print("MAY DUNG VI KHONG CON DUONG DI!!!")
            break
        
        history.append((matrix.copy(), row, col))
        
        if matrix[row, col] == 1:
            print("VI TRI NHA BAN TIEN HANH LAM SACH")
            matrix[row, col] = 0
        
        valid_move = []
        
        for move in moves:

            new_mat = check(matrix, move[0], row, col)

            repeated = False

            for old_matrix, old_row, old_col in history:

                if np.array_equal(new_mat, old_matrix) and move[1] == old_row and move[2] == old_col:
                    repeated = True
                    break

            if not repeated:
                valid_move.append(move)
        
        moves = valid_move
        
        if len(valid_move) == 0:
            print("DUNG HOAT DONG VI KHONG CON NUOC DI HOP LE!!!")
            break
        
            
        if 1 not in matrix:
            print(matrix)
            print("MAY DUNG HOAT DONG VI DA SACH!!!")
            break
        
        dir, row, col = random.choice(moves)
        
        print(f"MÁY HÚT BỤI DI CHUYỂN {dir}, ĐẾN VỊ TRÍ [{row}, {col}]")
        
        print(matrix)

In [30]:
matrix, row, col = create_mat()
actions(matrix, row, col)

VI TRI BAN DAU CUA MAY [0, 2]
[[1 2 1]
 [1 1 0]
 [0 1 0]]
VI TRI NHA BAN TIEN HANH LAM SACH
MÁY HÚT BỤI DI CHUYỂN DOWN, ĐẾN VỊ TRÍ [1, 2]
[[1 2 0]
 [1 1 0]
 [0 1 0]]
MÁY HÚT BỤI DI CHUYỂN LEFT, ĐẾN VỊ TRÍ [1, 1]
[[1 2 0]
 [1 1 0]
 [0 1 0]]
VI TRI NHA BAN TIEN HANH LAM SACH
MÁY HÚT BỤI DI CHUYỂN DOWN, ĐẾN VỊ TRÍ [2, 1]
[[1 2 0]
 [1 0 0]
 [0 1 0]]
VI TRI NHA BAN TIEN HANH LAM SACH
MÁY HÚT BỤI DI CHUYỂN RIGHT, ĐẾN VỊ TRÍ [2, 2]
[[1 2 0]
 [1 0 0]
 [0 0 0]]
MÁY HÚT BỤI DI CHUYỂN UP, ĐẾN VỊ TRÍ [1, 2]
[[1 2 0]
 [1 0 0]
 [0 0 0]]
MÁY HÚT BỤI DI CHUYỂN UP, ĐẾN VỊ TRÍ [0, 2]
[[1 2 0]
 [1 0 0]
 [0 0 0]]
DUNG HOAT DONG VI KHONG CON NUOC DI HOP LE!!!
